version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    # restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./fermematou.sql:/docker-entrypoint-initdb.d/fermematou.sql
      # Si vous avez un fichier de configuration personnalisé pour MySQL, décommentez cette ligne
      # - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    networks:
      - app_network

  backend:
    depends_on:
      - mysql
    build: ./api
    container_name: backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysql
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      # - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - app_network
    # command: sh -c "wait-for-it mysql:$MYSQLDB_DOCKER_PORT -- npm start"  # Attente avant de démarrer
    stdin_open: true
    tty: true

  # front-admin:
  #   depends_on:
  #     - backend
  #   build:
  #     context: ./front-admin
  #     args:
  #       - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
  #   container_name: admin
  #   ports:
  #     - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
  #   networks:
  #     - app_network

volumes:
  db:

networks:
  app_network:
    driver: bridge
